services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT:-3000}:3000"
    environment:
      SERVER_PORT: "3000"
      DB_HOST:     ${DB_HOST}
      DB_PORT:     ${DB_PORT:-5432}
      DB_NAME:     ${DB_NAME:-fsignal}
      DB_USER:     ${DB_USER:-fareltek}
      DB_PASS:     ${DB_PASS:-2580}
      ARCHIVE_PATH: /archive
    volumes:
      - fsignal-archive:/archive
    restart: unless-stopped

volumes:
  fsignal-archive:
