server:
  port: ${SERVER_PORT:3000}

spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fsignal}
    username: ${DB_USER:fareltek}
    password: ${DB_PASS:2580}
    pool:
      initial-size: 2
      max-size: 10

  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fsignal}
    user: ${DB_USER:fareltek}
    password: ${DB_PASS:2580}
    locations: classpath:db/migration

fsignal:
  archive:
    path: ${ARCHIVE_PATH:./archive}

logging:
  level:
    com.fareltek.fsignal: DEBUG
